[project]
name = "git-branch-deleter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "questionary>=2.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.9",
]
